### ISSUE TITLE
bot not starting 

### ISSUE THREAD

**Issue by jsjhax34** [nicl83/winbot#4]
```py
Config loaded succesfully!
Prefix: vm!
VM name: Windows Vista
Owner ID: 591994499069116417
Channel ID: 769678310438338611
Traceback (most recent call last):
  File "C:\Users\dolph\AppData\Local\Programs\Python\Python38-32\lib\site-packages\virtualbox\library_base.py", line 201, in _call_method
    ret = method(*in_params)
  File "C:\Users\dolph\AppData\Local\Temp\gen_py\3.8\88888888-1750-46F0-936E-BD127D5BC264x0x1x3\IVirtualBox.py", line 102, in FindMachine
    ret = self._oleobj_.InvokeTypes(1610743849, LCID, 1, (9, 0), ((8, 1),),aNameOrId
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'VirtualBoxWrap', "Could not find a registered machine named 'Windows Vista'", None, 0, -2135228415), None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 145, in <module>
    bot.vm = bot.vbox.find_machine(vm_name)
  File "C:\Users\dolph\AppData\Local\Programs\Python\Python38-32\lib\site-packages\virtualbox\library.py", line 8119, in find_machine
    machine = self._call("findMachine",
  File "C:\Users\dolph\AppData\Local\Programs\Python\Python38-32\lib\site-packages\virtualbox\library_base.py", line 192, in _call
    return self._call_method(method, in_p=in_p)
  File "C:\Users\dolph\AppData\Local\Programs\Python\Python38-32\lib\site-packages\virtualbox\library_base.py", line 220, in _call_method
    raise errobj
virtualbox.library_base.VBoxError: 0x80020009 (Could not find a registered machine named 'Windows Vista')```

doesn't seem to detect my vm

**Comment by jsjhax34** [comment]
removing the pr i did yesterday does nothing

**Comment by jsjhax34** [comment]
solution: api was fucked:tm: so you need to install virtualbox 5.2 and reinstall the api
